# Generated by Django 2.0.6 on 2018-08-23 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='问题')),
                ('pub_date', models.DateTimeField(verbose_name='提问时间')),
                ('BigIntegerField1', models.BigIntegerField(default=0, verbose_name='大整数字段')),
                ('BooleanField1', models.BooleanField(default=False, verbose_name='布尔字段')),
                ('CharField1', models.CharField(default='无', max_length=5, verbose_name='字符字段')),
                ('DateField1', models.DateField(default=None, verbose_name='日期字段')),
                ('DateTimeField1', models.DateTimeField(auto_now=True, verbose_name='日期时间字段')),
                ('DecimalField1', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='十进制小数字段')),
                ('EmailField1', models.EmailField(default='wu', max_length=10, verbose_name='电子邮箱字段')),
                ('FileField1', models.FileField(default='没有上传文件。', upload_to='File_home/%Y/%m/%d/', verbose_name='上传文件字段')),
                ('FloatField1', models.FloatField(default=0, verbose_name='小数字段')),
                ('ImageField1', models.ImageField(default='无', upload_to='File_home/%Y/%m/%d/', verbose_name='上传图片字段')),
                ('IntegerField1', models.IntegerField(default=0, verbose_name='整数字段')),
                ('GenericIPAddressField1', models.GenericIPAddressField(default='111.111.111.111', verbose_name='IP字段')),
                ('NullBooleanField1', models.NullBooleanField(verbose_name='空是否选项字段')),
                ('PositiveIntegerField1', models.PositiveIntegerField(default=337, verbose_name='正整数字段')),
                ('PositiveSmallIntegerField1', models.PositiveSmallIntegerField(default=1.7, verbose_name='正小数字段')),
                ('SlugField1', models.SlugField(default='ABC123', max_length=10, verbose_name='标签字段')),
                ('SmallIntegerField1', models.SmallIntegerField(default=30000, verbose_name='小整数字段')),
                ('TextField1', models.TextField(default='可输入很长的文本', verbose_name='文本字段')),
                ('URLField1', models.URLField(blank=True, verbose_name='URL字段')),
                ('UUIDField1', models.UUIDField(blank=True, null=True, verbose_name='UUID字段')),
            ],
            options={
                'verbose_name': '自带控件演示',
                'verbose_name_plural': '演示清单',
            },
        ),
        migrations.CreateModel(
            name='text_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text_Title', models.CharField(default='无', max_length=100, verbose_name='文章标题')),
                ('Text_Text', models.TextField(default='可输入很长的文本', verbose_name='文章正文')),
                ('Text_Demo', models.TextField(blank=True, default='可输入很长的文本', null=True, verbose_name='演示代码')),
                ('Text_Image', models.ImageField(blank=True, default='无', null=True, upload_to='File_home/%Y/%m/%d/', verbose_name='上传图片')),
                ('Text_File', models.FileField(blank=True, default='没有上传文件。', null=True, upload_to='File_home/%Y/%m/%d/', verbose_name='上传文件')),
                ('Text_ADD_DateTime', models.DateTimeField(auto_now=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '文本管理',
                'verbose_name_plural': '文本列表',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='ForeignKey1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_1.text_base', verbose_name='外键字段'),
        ),
        migrations.AddField(
            model_name='question',
            name='ManyToManyField1',
            field=models.ManyToManyField(blank=True, null=True, related_name='_question_ManyToManyField1_+', to='test_1.Question', verbose_name='多对多字段'),
        ),
        migrations.AddField(
            model_name='question',
            name='supervisor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of', to=settings.AUTH_USER_MODEL, verbose_name='1对1字段'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='1对1字段'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_1.Question'),
        ),
    ]
